update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,14 +1,6 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir>
 
-set -e
-
-version=8.6.2
-
-BUILD_DIR=$1
-CACHE_DIR=$2
-BUILDPACK_NAME=vips
-
 function indent() {
   c='s/^/       /'
   case $(uname) in
@@ -21,64 +13,51 @@ arrow() {
   sed -u 's/^/-----> /'
 }
 
-function vendor() {
-  binary="$1"
-  path="$2"
+BUILD_DIR=$1
+CACHE_DIR=$2
+ENVFILE=$3
+BP_DIR=`cd $(dirname $0); cd ..; pwd`
+TARBALL_URL=https://s3.amazonaws.com/proscia-viewer/vips-8.3.0%2Bopenslide-3.4.1.tar.gz
 
-  echo "Fetching $binary" | indent
-  echo 0
-  mkdir -p $path
-  echo 1
-  curl $binary -s -o - | tar xz -C $path -f -
-  echo 2
+echo "Installing libvips" | arrow
 
-  if [ -d "$path/bin" ]; then
-    export PATH=$path/bin:$PATH
-  fi
+cd $BUILD_DIR
 
-  if [ -d "$path/lib/pkgconfig" ]; then
-    # pkg-config should handle compiler options (if used)
-    export PKG_CONFIG_PATH="$path/lib/pkgconfig:$PKG_CONFIG_PATH"
-  fi
+output_dir="${BUILD_DIR}/vendor/vips"
+# Output library also to temp dir accordingly to pkg-config paths
+temp_app_dir="/app/vendor/vips"
+mkdir -p $output_dir
+mkdir -p $temp_app_dir
 
-  # standard paths
-  export CPPPATH="$path/include:$CPPPATH"
-  export CPATH="$path/include:$CPATH"
-  export LIBRARY_PATH="$path/lib:$LIBRARY_PATH"
+echo "Downloading libvips from $TARBALL_URL and unpacking" | indent
+curl -s $TARBALL_URL | tar xz -C $output_dir
 
-  export LD_LIBRARY_PATH="$path/lib:$LD_LIBRARY_PATH"
-  echo 3
-}
+echo "Downloading additional dependencies" | indent
+curl -s https://s3.amazonaws.com/proscia-viewer/additional_deps.tar.gz.enc -O
+openssl enc -d -aes-256-cbc -in additional_deps.tar.gz.enc -out additional_deps.tar.gz -pass file:$ENVFILE/DEPENDENCIES_KEY -md md5
+tar xzf additional_deps.tar.gz -C $output_dir
 
-echo "Vendoring binaries" | arrow
+if [ $? != 0 ]; then
+  echo "Error downloading vips and unpacking to build dir" | indent
+  exit 1
+fi
 
-# vendor "wget https://kespry-packages.s3.amazonaws.com/vips/$STACK/libvips-$version.tgz" "$BUILD_DIR/vendor/vips" # FIXME: unharcode version
-vendor "wget https://github.com/libvips/libvips/releases/download/v8.8.0-rc3/vips-8.8.0-rc3.tar.gz" "$BUILD_DIR/vendor/vips"
+if [ $? != 0 ]; then
+  echo "Error downloading vips and unpacking to app dir" | indent
+  exit 1
+fi
+mkdir -p $BUILD_DIR/bin/
+cp -r $output_dir/bin/* $BUILD_DIR/bin/
 
-echo "Tweaking glib include paths" | arrow
+echo "libvips installed" | indent
 
-export CPPPATH="$BUILD_DIR/vendor/vips/include/glib-2.0:$BUILD_DIR/vendor/vips/lib/glib-2.0/include:$CPPPATH"
-export CPATH="$BUILD_DIR/vendor/vips/include/glib-2.0:$BUILD_DIR/vendor/vips/lib/glib-2.0/include:$CPATH"
+#echo "Creating new env var in $3" | indent
 
-echo "Configuring build environment" | arrow
+echo "\$PKG_CONFIG_PATH:/app/vendor/vips/lib/pkgconfig" > $3/PKG_CONFIG_PATH
 
-cat <<EOF > export
-export PATH="$PATH:\$PATH"
-export LD_LIBRARY_PATH="\$LD_LIBRARY_PATH:$LD_LIBRARY_PATH"
-export LIBRARY_PATH="\$LIBRARY_PATH:$LIBRARY_PATH"
-export PKG_CONFIG_PATH="\$PKG_CONFIG_PATH:$PKG_CONFIG_PATH"
-export CPPPATH="\$CPPPATH:$CPPPATH"
-export CPATH="\$CPATH:$CPATH"
-EOF
+#echo "Installing vips .profile.d files" | indent
 
-echo "Building runtime environment" | arrow
-mkdir -p $BUILD_DIR/.profile.d
+mkdir $BUILD_DIR/.profile.d
+cp -n $BP_DIR/.profile.d/* $BUILD_DIR/.profile.d/
 
-cat <<EOF > $BUILD_DIR/.profile.d/$BUILDPACK_NAME.sh
-export PATH="${PATH//$BUILD_DIR//app}:\$PATH"
-export LD_LIBRARY_PATH="\$LD_LIBRARY_PATH:${LD_LIBRARY_PATH//$BUILD_DIR//app}"
-export LIBRARY_PATH="\$LIBRARY_PATH:${LIBRARY_PATH//$BUILD_DIR//app}"
-export PKG_CONFIG_PATH="\$PKG_CONFIG_PATH:${PKG_CONFIG_PATH//$BUILD_DIR//app}"
-export CPPPATH="\$CPPPATH:${CPPPATH//$BUILD_DIR//app}"
-export CPATH="\$CPATH:${CPATH//$BUILD_DIR//app}"
-EOF
+#echo ".profile.d files installed" | indent
